export const SIDEBAR_ACTIVE = "SIDEBAR_ACTIVE";
export const SIDEBAR_CLOSED = "SIDEBAR_CLOSED";
export const SET_ACTIVE_PAGE = "SET_ACTIVE_PAGE";
export const GET_INITIAL_CALANDAR_DATA = "GET_INITIAL_CALANDAR_DATA";
export const GET_CALANDAR_NEXT = "GET_CALANDAR_NEXT";
export const GET_CALANDAR_PREV = "GET_CALANDAR_PREV";
export const INPUT_ACTIVE = "INPUT_ACTIVE";