export const UPDATE_TEMP_MONTH = "UPDATE_TEMP_MONTH";
export const INCREASE_DECREASE_MONTH = "INCREASE_DECREASE_MONTH";
export const SET_CURRENT_MONTH = "SET_CURRENT_MONTH";
//
export const FORMAT_CURRENT_DATE = "FORMAT_CURRENT_DATE";
export const UPDATE_CURRENT_DATE_HEADER = "UPDATE_CURRENT_DATE_HEADER";
//
export const ADD_TO_MAIN_SCHEDULE = "ADD_TO_MAIN_SCHEDULE";
export const ACTIVE_SCHEDULE_TAB = "ACTIVE_SCHEDULE_TAB";
export const DELETE_FROM_SCHEDULE = "DELETE_FROM_SCHEDULE";
export const EDIT_SCHEDULE_TAB = "EDIT_SCHEDULE_TAB";
// export const UPDATE_EDIT_SCHEDULE_TAB = "UPDATE_EDIT_SCHEDULE_TAB";