export const UPDATE_TEMP_MONTH = "UPDATE_TEMP_MONTH";
export const INCREASE_DECREASE_MONTH = "INCREASE_DECREASE_MONTH";
export const SET_CURRENT_MONTH = "SET_CURRENT_MONTH";
//
export const FORMAT_CURRENT_DATE = "FORMAT_CURRENT_DATE";
export const UPDATE_CURRENT_DATE_HEADER = "UPDATE_CURRENT_DATE_HEADER";
